bind 127.0.0.1
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300
daemonize no
supervised no
loglevel notice
logfile D:/internship-platform/logs/redis/redis.log
databases 16
dir D:/internship-platform/data/redis
save 900 1
save 300 10
save 60 10000
appendonly no
